//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyDatabaseToOtherDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopyDatabaseToOtherDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;__CennikiDostawcow&apos;) AND type in (N&apos;U&apos;))
        ///BEGIN DROP TABLE [dbo].[__CennikiDostawcow] END
        ///
        ///CREATE TABLE [dbo].[__CennikiDostawcow](
        ///	[id] [int] IDENTITY(1,1) NOT NULL,
        ///	[id_produktu] [int] NULL,
        ///	[id_dostawcy] [int] NULL,
        ///	[KodDostawcy] [nvarchar](50) NOT NULL,
        ///	[KodProducenta] [nvarchar](50) NOT NULL,
        ///	[Nazwa] [nvarchar](max) NULL,
        ///	[Grupa] [nvarchar](50) NULL,
        ///	[Stan] [decimal](18, 0) NOT NULL,
        ///	[CenaNetto] [money] NOT NULL,
        ///	[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateExampleTable {
            get {
                return ResourceManager.GetString("CreateExampleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @table_name SYSNAME
        ///SELECT @table_name = &apos;{0}&apos;
        ///
        ///DECLARE 
        ///      @object_name SYSNAME
        ///    , @object_id INT
        ///
        ///SELECT 
        ///      @object_name = &apos;[&apos; + s.name + &apos;].[&apos; + o.name + &apos;]&apos;
        ///    , @object_id = o.[object_id]
        ///FROM sys.objects o WITH (NOWAIT)
        ///JOIN sys.schemas s WITH (NOWAIT) ON o.[schema_id] = s.[schema_id]
        ///WHERE s.name + &apos;.&apos; + o.name = @table_name
        ///    AND o.[type] = &apos;U&apos;
        ///    AND o.is_ms_shipped = 0
        ///
        ///DECLARE @SQL NVARCHAR(MAX) = &apos;&apos;
        ///
        ///;WITH index_column AS 
        ///(
        ///    SELECT 
        ///          ic.[ob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateOfTable {
            get {
                return ResourceManager.GetString("CreateOfTable", resourceCulture);
            }
        }
    }
}
